AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: lambda
Parameters:
  Env:
    Type: String
    Default: dev
  Project:
    Type: String
    Default: default-project
  RoleName:
    Type: String
    Default: default-Role

Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub 'send-slack-${Env}'
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: './src/send-slack'
      Description: !Sub 'send-slack-${Env}'
      Environment:
        Variables:
          ENV: !Sub ${Env}
          ACCOUNT_ID: !Sub ${AWS::AccountId}
      MemorySize: 1024
      Timeout: 600
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/service-role/${RoleName}'
      Tags:
        Env: !Sub ${Env}
        project: !Sub ${Project}
      Layers:
        - !Ref CommonLayer

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: python modules Layer
      ContentUri: ./layers/common
      CompatibleRuntimes:
        - python3.7
        - python3.6